version : 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: cast(date_date as timestamp)
        identifier: raw_gz_sales
        description: greenweez sales data
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key
            tests:
              - unique
              - not_null
      - name: product
        identifier: raw_gz_product
        description : greenweez product data
        columns:
          - name: products_id
            description : primary key
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: greenweez shipping data
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
      - name: facebook
        identifier: raw_gz_facebook
        description : greenweez facebook campaign data
      - name: adwords
        identifier: raw_gz_adwords
        description : greenweez adwords campaign data
      - name: bing
        identifier: raw_gz_bing
        description : greenweez bing campaign data
      - name: criteo
        identifier: raw_gz_criteo
        description : greenweez criteo campaign data

models:
  - name: int_campaigns
    tests:
      - unique:
          column_name: "(date_date || '-' || campaign_key)"
      - not_null:
          column_name: campaign_key
  - name: int_campaigns_day
    tests:
      - unique:
          column_name: date_date